App\Entity\Direccion:
    properties:
        calle:
            - NotBlank: ~

        numero:
            - NotBlank: ~

        puertaPisoEscalera:
            - NotBlank: ~

        codPostal:
            - NotBlank: ~